export class OrderInitiation{
    OrderID:any;
    OrderNumber:any;
    CustomerID:any;
    IsNew:any=true;
    Fault:any=1;
    Evidence:any=true;
    Company:any;
    Reference:any;
    OrderType:any;
    OrderStatus:any;
    OrderDate:any;
    NumbOfBlinds:any;
    ConsignNoteNum:any;
    CompleteDate:any;
    DeliveryDate:any;
    DepartureDate:any;
    ArrivalDate:any;
    OrderM2:any;
    OldOrderNumber:any;
    Notes:any;
}