export class OrderInitiation{
    OrderID:any;
    OrderNumber:any;
    CustomerID:any;
    IsNew:any=true;
    Fault:any="Factory";
    Evidence:any=true;
    Company:any;
    Reference:any;
    OrderTypeID:any;
    OrderStatusID:any;
    OrderStatus:any;
    OrderDate:any;
    NumbOfBlinds:any;
    ConsignNoteNum:any;
    CompleteDate:any;
    DeliveryDate:any;
    DepartureDate:any;
    ArrivalDate:any;
    OrderM2:any;
    OldOrderNumber:any;
    Notes:any;
    BlindTypeID:any=0;
    BlindTypeText:any;
    Transport:any="Sea";
    IsApproved:any;
}