/*
 * jQuery Chop Slider v.2.0.5.Free
 
 * http://www.idangero.us/cs
 *
 * Copyright 2011, Vladimir Kharlampidi
 * The iDangero.us
 * http://www.idangero.us
 
 * Licensed under the iDangero.us Regular License.
 * Licensing Terms: http://www.idangero.us/index.php?content=article&id=21
 
 * Released on: September 1, 2011
 */

(function(d){d.fn.chopSlider=function(b){var y,z,h;function F(){for(var d=navigator.userAgent,a=!1,i=0;i<=b.mobileUAs.length-1;i++)d.indexOf(b.mobileUAs[i])>=0&&(a=!0);return a}function C(){return d.chopSlider.hasCSS3()&&!b.disableCSS3}function t(b,a){if(a/b!=Math.floor(a/b))for(var d=0;d<=b;d++){if(a/(b+d)==Math.floor(a/(b+d))){b+=d;break}if(a/(b-d)==Math.floor(a/(b-d))){b-=d;break}}return b}function A(b,a,d,n){if(a==0)return a;if(a=="middle"){if(b=="vertical"||b=="vertical3D")a=Math.round(n/2);
if(b=="horizontal"||b=="horizontal3D")a=Math.round(d/2);if(b=="multi"||b=="multiFlipV"||b=="multiFlipH"||b=="multiFlip"||b=="sphere")a=Math.round(d*n/2);return a}if(a=="end"){if(b=="vertical"||b=="vertical3D")a=n;if(b=="horizontal"||b=="horizontal3D")a=d;if(b=="multi"||b=="multiFlipV"||b=="multiFlipH"||b=="multiFlip"||b=="sphere")a=d*n-1}return a}function H(b,a,d){b.returnTransformCallback=a;this.runCallback=function(){var a=setTimeout(function(){b.returnTransformCallback();clearTimeout(a)},d.time+
d.delay)}}function G(){d.chopSlider.autoplay=setTimeout(function(){B("next",b)},b.autoplayDelay)}function B(f,a,i){function n(){k.html("");r.html("").css({display:"none"});i>=0?(d(b.activeQClass).removeClass(b.activeSlideClass),d(m+":eq("+i+")").addClass(b.activeSlideClass).show()):f=="next"?d(b.activeQClass).next(m).length>0?d(b.activeQClass).css({display:"none"}).removeClass(b.activeSlideClass).next(m).addClass(b.activeSlideClass).show():(d(b.activeQClass).removeClass(b.activeSlideClass),d(m+":eq(0)").addClass(b.activeSlideClass).show()):
d(b.activeQClass).prev(m).length>0?d(b.activeQClass).removeClass(b.activeSlideClass).prev(m).addClass(b.activeSlideClass).show():(d(b.activeQClass).removeClass(b.activeSlideClass),d(m+":last").addClass(b.activeSlideClass).show());a.hideTriggers&&(y.fadeIn(600),z.fadeIn(600));h.hide();D=0;a.useCaptions&&chopSliderShowDescr();if(a.onEnd)a.onEnd();a.autoplay&&G();d.extend(a,s);a.hidePagination&&d(a.sliderPagination).parent().fadeIn(600)}a.sliderLoader.css({left:a.container.offset().left,top:a.container.offset().top});
!i&&i!==0&&(i=f=="next"?d(b.activeQClass).next(m).length>0?d(b.activeQClass).next(m).index():0:d(b.activeQClass).prev(m).length>0?d(b.activeQClass).prev(m).index():d(m+":last").index());if(D!=1){D=1;var s={};d.extend(s,a);if(a.transition||a.t2D){if(a.t2D)a.transition=a.t2D;if(a.transition instanceof Array)a.transition=a.transition[Math.floor(Math.random()*a.transition.length)];if(typeof a.transition=="string"&&a.transition.indexOf("random")>=0){var e=a.transition.split("{")[1].split("}")[0],p=-2;
for(prop in csTransitions[e])p++;a.transition=csTransitions[e][Math.round(Math.random()*p)]}if(a.transition.vPieces=="2*hPieces")a.transition.vPieces=a.transition.hPieces*2;if(a.transition.vPieces=="3*hPieces")a.transition.vPieces=a.transition.hPieces*3;d.extend(a,a.transition);a.vPieces=t(a.vPieces,a.width);a.hPieces=t(a.hPieces,a.height);if(a.squareMode&&a.width/a.vPieces!=a.height/a.hPieces){_FvPieces=a.width*a.hPieces/a.height;if(_FvPieces!=Math.floor(_FvPieces))for(e=a.hPieces;e<=2*a.hPieces;e++)if(a.hPieces=
t(a.hPieces+e,a.height),p=a.width*a.hPieces/a.height,p==Math.floor(p)){_FvPieces=p;break}if(_FvPieces<20)a.vPieces=_FvPieces}a.startFrom=A(a.type,a.startFrom,a.hPieces,a.vPieces)}if(a.noCSS3&&!d.chopSlider.hasCSS3()){if(a.noCSS3 instanceof Array)a.noCSS3=a.noCSS3[Math.floor(Math.random()*a.noCSS3.length)];if(typeof a.noCSS3=="string"&&a.noCSS3.indexOf("random")>=0){e=a.noCSS3.split("{")[1].split("}")[0];p=-2;for(prop in csTransitions[e])p++;a.noCSS3=csTransitions[e][Math.round(Math.random()*p)]}if(a.noCSS3.vPieces)a.noCSS3.vPieces=
t(a.noCSS3.vPieces,a.width);if(a.noCSS3.hPieces)a.noCSS3.hPieces=t(a.noCSS3.hPieces,a.height);a.noCSS3.startFrom=A(a.noCSS3.type,a.noCSS3.startFrom,a.noCSS3.hPieces,a.noCSS3.vPieces);d.extend(a,a.noCSS3)}if(d.chopSlider.has3D()&&a.t3D){if(a.t3D instanceof Array)a.t3D=a.t3D[Math.floor(Math.random()*a.t3D.length)];if(typeof a.t3D=="string"&&a.t3D.indexOf("random")>=0){e=a.t3D.split("{")[1].split("}")[0];p=-2;for(prop in csTransitions[e])p++;a.t3D=csTransitions[e][Math.round(Math.random()*p)]}if(a.t3D.vPieces)a.t3D.vPieces=
t(a.t3D.vPieces,a.width);if(a.t3D.hPieces)a.t3D.hPieces=t(a.t3D.hPieces,a.height);a.t3D.startFrom=A(a.t3D.type,a.t3D.startFrom,a.t3D.hPieces,a.t3D.vPieces);e={top:"#999",right:"#999",bottom:"#333",left:"#555"};a.t3D.showFaces=a.t3D.showFaces===!0||a.t3D.showFaces===!1?a.t3D.showFaces:!0;a.t3D.type=a.t3D.type||"vertical3d";if(a.t3D.type=="multiFlipV")a.t3D.type="multiFlip",a.t3D.flipV=!0;if(a.t3D.type=="multiFlipH")a.t3D.type="multiFlip",a.t3D.flipV=!1;a.t3D.rotateMid=a.t3D.rotateMid||a.t3D.rotateMid===
0?a.t3D.rotateMid:0;a.t3D.rotateZ=a.t3D.rotateZ||0;a.t3D.scaleY=a.t3D.scaleY||a.t3D.scaleY===0?a.t3D.scaleY:1;a.t3D.scaleX=a.t3D.scaleX||a.t3D.scaleX===0?a.t3D.scaleX:1;a.t3D.scaleZ=a.t3D.scaleZ||a.t3D.scaleZ===0?a.t3D.scaleZ:1;a.t3D.translateZ=a.t3D.translateZ||a.t3D.translateZ===0?a.t3D.translateZ:0;a.t3D.faces=a.t3D.faces&&!a.full3D?d.extend(e,a.t3D.faces):e;d.extend(a,a.t3D)}if(a.mobile&&F()){if(a.mobile instanceof Array)a.mobile=a.mobile[Math.floor(Math.random()*a.mobile.length)];if(typeof a.mobile==
"string"&&a.mobile.indexOf("random")>=0){e=a.mobile.split("{")[1].split("}")[0];p=-2;for(prop in csTransitions[e])p++;a.mobile=csTransitions[e][Math.round(Math.random()*p)]}if(a.mobile.vPieces)a.mobile.vPieces=t(a.mobile.vPieces,a.width);if(a.mobile.hPieces)a.mobile.hPieces=t(a.mobile.hPieces,a.height);a.mobile.startFrom=A(a.mobile.type,a.mobile.startFrom,a.mobile.hPieces,a.mobile.vPieces);d.extend(a,a.mobile)}if(a.xOffset=="random"&&a.type!="horizontal")a.xOffset=Math.round(Math.random()*a.width/
2)-a.width/4;if(a.xOffset=="random"&&a.type=="horizontal")a.xOffset=0;if(a.yOffset=="random")a.yOffset=Math.round(Math.random()*a.height/2)-a.height/4;if(a.translateX=="random")a.translateX=Math.round(Math.random()*a.width/2)-a.width/4;if(a.translateY=="random")a.translateY=Math.round(Math.random()*a.height/2)-a.height/4;if(a.rotate=="random")a.rotate=a.rotateSymmetric==!1?Math.round(Math.random()*100)-50:Math.round(Math.random()*360)-180;if(a.scaleX=="random")a.scaleX=Math.round(Math.random()*200-
100)/100;if(a.scaleY=="random"&&a.type=="multi"&&(s.scaleX=="random"||a.transition.scaleX=="random"))a.scaleY=a.scaleX;if(a.scaleY=="random"&&a.type=="multi"&&(s.scaleX!="random"||a.transition.scaleX!="random"))a.scaleY=Math.round(Math.random()*200-100)/100;if(a.scaleY=="random"&&a.type!="multi")a.scaleY=Math.round(Math.random()*200-100)/100;if(a.multiDelay=="random")a.multiDelay=Math.round(Math.random()),a.multiDelay=a.multiDelay==0?"linear":"progressive";if(a.startFrom=="random"&&a.type=="multi")a.startFrom=
Math.round(Math.random()*a.hPieces*a.vPieces);if(a.startFrom=="random"&&a.type=="vertical")a.startFrom=Math.round(Math.random()*a.vPieces);if(a.startFrom=="random"&&a.type=="horizontal")a.startFrom=Math.round(Math.random()*a.hPieces);chopSliderHideDescr=function(){a.hideCaptions&&(d(a.showCaptionIn).hide(),a.captionTransform&&d(a.showCaptionIn).csTransform({transform:a.captionTransform,time:300,delay:0}))};chopSliderShowDescr=function(){var b=d(a.everyCaptionIn).eq(d(a.slide+a.activeQClass).index()).html();
d.trim(b)!=""&&(d(a.showCaptionIn).html(b),a.hideCaptions&&(C()&&a.captionTransform&&d(a.showCaptionIn).fadeIn(10,function(){d(this).csTransform({transform:"scale(1,1) translate(0px,0px) rotate(0deg)",time:600,delay:0})}),d(a.showCaptionIn).fadeIn(300)))};a.hideTriggers&&(y.hide(),z.hide());if(a.onStart)a.onStart();a.useCaptions&&chopSliderHideDescr();a.hidePagination&&d(a.sliderPagination).parent().hide();var u=d(m+b.activeQClass);if(i>=0)var o=d(m+":eq("+i+")");else f=="next"?(o=u.next(m),o.length==
0&&(o=d(m+":eq(0)"))):(o=u.prev(m),o.length==0&&(o=d(m+":last")));b.sliderPagination&&(d(b.activeQPaginationClass).removeClass(b.activePaginationClass),d(b.sliderPagination).eq(o.index()).addClass(b.activePaginationClass));u.hide();h.show();a.prevTransition&&f=="prev"&&d.extend(a,a.prevTransition);if(a.halfTransition)var q=!0;a.startFrom=A(a.type,a.startFrom,a.hPieces,a.vPieces);a.forceParameters&&d.extend(a,a.forceParameters);switch(a.type){case "multi":for(var k=h.find(".dummy-first"),r=h.find(".dummy-last"),
e=1;e<=a.vPieces*a.hPieces;e++)k.append("<div ></div>"),q||r.append("<div></div>");q&&o.css({display:"block"});var j;if(a.startFrom<=0)a.startFrom=0;switch(a.multiDelay){case "linear":j=a.startFrom;a.startFrom>=a.vPieces*a.hPieces-1&&(j=a.vPieces*a.hPieces-1);break;case "progressive":e=a.vPieces*a.vPieces/5+a.hPieces-3;if(a.startFrom>=a.vPieces*a.hPieces-1)a.startFrom=a.vPieces*a.hPieces-1;j=Math.round(a.startFrom/a.hPieces/a.vPieces*e);j>e&&(j=e)}var w;w=a.startFrom>=a.vPieces*a.hPieces/2?0:a.hPieces*
a.vPieces-1;j!=Math.round(j)&&(j=Math.round(j));k.children("div").each(function(){var b=d(this).index(),f=b-Math.floor(b/a.vPieces)*a.vPieces,e=Math.floor(b/a.vPieces);d(this).css({width:a.width/a.vPieces,height:a.height/a.hPieces,position:"absolute",top:a.height/a.hPieces*e,left:a.width/a.vPieces*f,"background-image":"url("+u.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*f+"px "+-a.height/a.hPieces*e+"px",opacity:1,borderRadius:"0px 0px 0px 0px"});if(C())d(this).csTransform({transform:"rotate(0deg) scaleY(1) scaleX(1) translate(0px,0px)",
delay:20,time:0,ease:a.ease1,origin:a.origin,add:"left, top, border-radius, opacity"},function(){var g="rotate("+(!a.rotateSymmetric?-(-a.rotate+a.rotate*2*f/(a.vPieces-1)):a.rotate)+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+") translate("+a.translateX+"px,"+a.translateY+"px)",i;switch(a.multiDelay){case "linear":i=Math.abs(a.pieceDelay*(j-b));break;case "progressive":if(i=Math.abs(a.pieceDelay*(j-(e*a.vPieces/5+f))),a.startFrom==a.vPieces*a.hPieces-1)var h=Math.abs(a.pieceDelay*(j-(a.hPieces*
a.vPieces/5+a.vPieces)))}h&&(i-=h);d(this).css({left:(a.width+a.xOffset*2)/a.vPieces*f-a.xOffset,top:a.yOffset*2*e/a.hPieces-a.yOffset+a.height/a.hPieces*e,opacity:q?a.halfTransitionOpacity:1,borderRadius:l!="-o-"?a.borderRadius:""}).csTransform({transform:g,delay:i,time:a.dur1,ease:a.ease1,origin:a.origin,add:"left, top, border-radius, opacity"},function(){q?b==w&&n():r.css({display:"block"}).find("div:eq("+b+")").css({width:a.width/a.vPieces,position:"absolute",left:(a.width+a.xOffset*2)/a.vPieces*
f-a.xOffset,top:a.yOffset*2*e/a.hPieces-a.yOffset+a.height/a.hPieces*e,height:a.height/a.hPieces,display:"none","background-image":"url("+o.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*f+"px "+-a.height/a.hPieces*e+"px",borderRadius:l!="-o-"?a.borderRadius+"px "+a.borderRadius+"px "+a.borderRadius+"px "+a.borderRadius+"px":""}).csTransform({transform:g,delay:0,time:0,ease:a.ease2,origin:a.origin,add:"left, top, border-radius"},function(){d(this).delay(a.xFadeDelay).fadeIn(a.dur2,
function(){k.children("div:eq("+b+")").hide();d(this).css({top:a.height/a.hPieces*e,left:a.width/a.vPieces*f,borderRadius:l!="-o-"?"0px 0px 0px 0px":""}).csTransform({transform:"rotate(0deg) scaleY(1) scaleX(1) translate(0px,0px)",time:a.dur3,delay:0,ease:a.ease2,origin:a.origin,add:"left, top, border-radius"},function(){b==w&&n()})})})});l=="-o-"&&q&&d(this).delay(i).animate({"border-radius":a.borderRadius},a.dur1)});else{if(a.scaleX<0)a.scaleX=0;if(a.scaleY<0)a.scaleY=0;var g={left:(a.width+a.xOffset*
2)/a.vPieces*f-a.xOffset,top:a.yOffset*2*e/a.hPieces-a.yOffset+a.height/a.hPieces*e,width:a.scaleX*d(this).width(),height:a.scaleY*d(this).height(),opacity:q?a.halfTransitionOpacity:1},i;switch(a.multiDelay){case "linear":i=Math.abs(a.pieceDelay*(j-b));break;case "progressive":if(i=Math.abs(a.pieceDelay*(j-(e*a.vPieces/5+f))),a.startFrom==a.vPieces*a.hPieces-1)var h=Math.abs(a.pieceDelay*(j-(a.hPieces*a.vPieces/5+a.vPieces)))}h&&(i-=h);d(this).delay(i).animate(g,a.dur1,function(){if(q)b==w&&n();else{r.show();
var d={top:a.height/a.hPieces*e,left:a.width/a.vPieces*f,width:a.width/a.vPieces,height:a.height/a.hPieces};r.find("div:eq("+b+")").css({width:a.scaleX*a.width/a.vPieces,position:"absolute",left:(a.width+a.xOffset*2)/a.vPieces*f-a.xOffset,top:a.yOffset*2*e/a.hPieces-a.yOffset+a.height/a.hPieces*e,height:a.scaleY*a.height/a.hPieces,display:"none","background-image":"url("+o.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*f+"px "+-a.height/a.hPieces*e+"px"}).delay(a.xFadeDelay).fadeIn(a.dur2,
function(){k.children("div:eq("+b+")").hide()}).animate(d,a.dur3,function(){b==w&&n()})}})}});break;case "multiFlip":k=h.find(".dummy-first");r=h.find(".dummy-last");for(e=1;e<=a.vPieces*a.hPieces;e++)k.append('<div><div class="cs-right-face"></div><div class="cs-left-face"></div><div class="cs-bot-face"></div><div class="cs-top-face"></div><div class="cs-old-face"></div><div class="cs-new-face"></div></div>');h.css({perspective:"1200","perspective-origin":"50% 50%","-webkit-perspective":"1200","-webkit-perspective-origin":"50% 50%"});
if(a.animateContainer){var v="rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1) translate3d(0px,0px,0px)";k.csTransform({transform:v,delay:0,time:0,origin:"50% 50%"},function(){d(this).css({"-webkit-transform-style":"preserve-3d","transform-style":"preserve-3d"}).csTransform({transform:a.animateContainer,time:a.dur1,delay:0,origin:"50% 50%"},function(){d(this).csTransform({time:a.dur3,delay:a.containerDelay,transform:v,origin:"50% 50%"})})})}if(a.startFrom<=0)a.startFrom=0;switch(a.multiDelay){case "linear":j=
a.startFrom;a.startFrom>=a.vPieces*a.hPieces-1&&(j=a.vPieces*a.hPieces-1);break;case "progressive":e=a.vPieces*a.vPieces/5+a.hPieces-3,j=Math.round(a.startFrom/a.hPieces/a.vPieces*e),j>e&&(j=e)}w=a.startFrom>=a.vPieces*a.hPieces/2?0:a.hPieces*a.vPieces-1;j!=Math.round(j)&&(j=Math.round(j));j<=0&&(j=0);var x=a.showFaces?10:0;k.children("div").each(function(){var b=d(this).index(),f=b-Math.floor(b/a.vPieces)*a.vPieces,e=Math.floor(b/a.vPieces);d(this).css({width:a.width/a.vPieces,height:a.height/a.hPieces,
position:"absolute",top:a.height/a.hPieces*e,left:a.width/a.vPieces*f,zIndex:(f>=a.vPieces/2?-f:f)-e,"transform-style":"preserve-3d","-webkit-transform-style":"preserve-3d","-webkit-perspective-origin":"50% 50%","perspective-origin":"50% 50%"}).children("div.cs-old-face").each(function(){d(this).css({width:a.width/a.vPieces,height:a.height/a.hPieces,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",top:0,left:0,zIndex:9,"background-image":"url("+u.find("img").attr("src")+
")",backgroundPosition:-a.width/a.vPieces*f+"px "+-a.height/a.hPieces*e+"px"})}).end().children("div.cs-new-face").each(function(){d(this).csTransform({transform:a.flipV?"rotateX(180deg) translateZ("+x+"px)":"rotateX(180deg) rotateZ(180deg) translateZ("+x+"px)",origin:"center center"}).css({width:a.width/a.vPieces,height:a.height/a.hPieces,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,backgroundPosition:-a.width/a.vPieces*f+"px "+
-a.height/a.hPieces*e+"px"});d(this).css({"background-image":"url("+o.find("img").attr("src")+")"})}).end();a.showFaces&&(d(this).children("div.cs-top-face").each(function(){d(this).csTransform({transform:"rotateX(90deg) translateY(-10px) translateZ(0px)",origin:"center top"}).css({width:a.width/a.vPieces,height:10,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,background:a.t3D.faces.top})}).end(),d(this).children("div.cs-bot-face").each(function(){d(this).csTransform({transform:"rotateX(-90deg) translateY(10px) translateZ("+
(a.height/a.hPieces-10)+"px)",origin:"center bottom"}).css({width:a.width/a.vPieces,height:10,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,background:a.t3D.faces.bottom})}).end().children("div.cs-left-face").each(function(){d(this).csTransform({transform:"rotateY(-90deg) translateX(-10px)",origin:"left center"}).css({width:10,height:a.height/a.hPieces,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",
top:0,left:0,background:a.t3D.faces.left,zIndex:-f*2})}).end().children("div.cs-right-face").each(function(){d(this).csTransform({transform:"rotateY(90deg)",origin:"left center"}).css({width:10,height:a.height/a.hPieces,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",top:0,left:a.width/a.vPieces,background:a.t3D.faces.right,zIndex:10})}).end());d(this).csTransform({transform:"rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleY(Z) translate3d(0px,0px,0px)",
delay:100,time:0,ease:a.ease1,origin:"center center",add:"left, top"},function(){if(a.vPieces!=1)var g=!a.rotateSymmetric?-(-a.rotate+a.rotate*2*f/(a.vPieces-1)):a.rotate,i=!a.rotateSymmetric?-a.rotateZ+a.rotateZ*2*f/(a.vPieces-1):a.rotateZ;else g=a.rotate,i=a.rotateZ;var h,k;a.flipV?(g="rotateX("+a.rotateMid+"deg) rotateY("+i+"deg) rotateZ("+g+"deg) scaleX("+a.scaleX+") scaleY("+a.scaleY+") scaleZ("+a.scaleZ+")  translate3d("+a.translateX+"px,"+a.translateY+"px,"+(a.translateZ+x)+"px)",k="rotateX(180deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1)  translate3d(0px,0px,"+
x+"px)"):(g="rotateX("+i+"deg) rotateY("+a.rotateMid+"deg) rotateZ("+g+"deg) scaleX("+a.scaleX+") scaleY("+a.scaleY+") scaleZ("+a.scaleZ+")  translate3d("+a.translateX+"px,"+a.translateY+"px,"+(a.translateZ+x)+"px)",k="rotateX(0deg) rotateY(180deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1)  translate3d(0px,0px,"+x+"px)");switch(a.multiDelay){case "linear":h=Math.abs(a.pieceDelay*(j-b));break;case "progressive":if(h=Math.abs(a.pieceDelay*(j-(e*a.vPieces/5+f))),a.startFrom==a.vPieces*a.hPieces-1)var l=
Math.abs(a.pieceDelay*(j-(a.hPieces*a.vPieces/5+a.vPieces)))}l&&(h-=l);d(this).css({left:(a.width+a.xOffset*2)/a.vPieces*f-a.xOffset,top:a.yOffset*2*e/a.hPieces-a.yOffset+a.height/a.hPieces*e}).csTransform({transform:g,delay:h,time:a.dur1,ease:a.ease1,origin:"center center",add:"left, top"},function(){d(this).css({top:a.height/a.hPieces*e,left:a.width/a.vPieces*f}).csTransform({transform:k,time:a.dur3,delay:a.xFadeDelay,ease:a.ease2,origin:"center center",add:"left, top"},function(){b==w&&n()})})})});
break;case "vertical3D":k=h.find(".dummy-first");r=h.find(".dummy-last");for(e=1;e<=a.vPieces;e++)k.append('<div><div class="cs-right-face"></div><div class="cs-left-face"></div><div class="cs-bot-face"></div><div class="cs-old-face"></div><div class="cs-new-face"></div></div>');h.css({"-webkit-perspective":"1200","-webkit-perspective-origin":"50% 50%",perspective:"1200","perspective-origin":"50% 50%"});a.animateContainer&&(h.css({"-webkit-perspective":"1200",perspective:"1200"}),v="rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1) translate3d(0px,0px,0px)",
k.csTransform({transform:v,delay:100,time:0,origin:"50% 50%"},function(){d(this).css({"-webkit-transform-style":"preserve-3d","transform-style":"preserve-3d"}).csTransform({transform:a.animateContainer,time:a.dur1,delay:0,origin:"50% 50%"},function(){d(this).csTransform({time:a.dur3,delay:a.containerDelay,transform:v,origin:"50% 50%"})})}));k.children("div").each(function(){var b=d(this).index();d(this).css({width:a.width/a.vPieces,height:a.height,position:"absolute",top:0,left:a.width/a.vPieces*
b,zIndex:b>=a.vPieces/2?-b:b,"transform-style":"preserve-3d","-webkit-transform-style":"preserve-3d","-webkit-perspective-origin":"50% 50%","perspective-origin":"50% 50%"}).children("div.cs-old-face").each(function(){d(this).css({width:a.width/a.vPieces,height:a.height,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",top:0,left:0,zIndex:9,"background-image":"url("+u.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*b+"px top"})}).end().children("div.cs-new-face").each(function(){d(this).csTransform({transform:"rotateX(90deg) translateY(-"+
a.height+"px)",origin:"center top"}).css({width:a.width/a.vPieces,height:a.height,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,"background-image":"url("+o.find("img").attr("src")+")",backgroundPosition:-a.width/a.vPieces*b+"px top"})}).end();a.showFaces&&d(this).children("div.cs-bot-face").each(function(){d(this).csTransform({transform:"rotateX(-90deg) translateY("+a.height+"px)",origin:"center bottom"}).css({width:a.width/a.vPieces,
height:a.height,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,background:a.t3D.faces.bottom})}).end().children("div.cs-right-face").each(function(){d(this).csTransform({transform:"rotateY(90deg)",origin:"left center"}).css({width:a.height,height:a.height,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",top:0,left:a.width/a.vPieces,background:a.t3D.faces.right,zIndex:10})}).end().children("div.cs-left-face").each(function(){d(this).csTransform({transform:"rotateY(-90deg) translateX(-"+
a.height+"px)",origin:"left center"}).css({width:a.height,height:a.height,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",top:0,left:0,background:a.t3D.faces.left,zIndex:-b*2})}).end();d(this).csTransform({transform:"rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleY(1) scaleX(1) scaleZ(1) translate3d(0px,0px,0px)",delay:0,time:100,ease:a.ease1,origin:"center center",add:"left, top"},function(){if(a.vPieces>1)var f=!a.rotateSymmetric?-a.rotate+a.rotate*2*b/
(a.vPieces-1):a.rotate,e=-a.rotateZ+a.rotateZ*2*b/(a.vPieces-1);else f=a.rotate,e=a.rotateZ;var g=a.vPieces;if(a.startFrom>=g-1)a.startFrom=g-1;if(a.startFrom<=0)a.startFrom=0;var i=Math.abs(a.pieceDelay*(a.startFrom-b)),h=a.dur3==0?a.height/2:0;d(this).css({left:(a.width+a.xOffset*2)/a.vPieces*b-a.xOffset,top:a.yOffset}).csTransform({transform:"rotateX("+a.rotateMid+"deg)  rotateZ("+e+"deg) rotateY("+f+"deg) scaleX("+a.scaleX+") scaleY("+a.scaleY+") scaleZ("+a.scaleZ+") translate3d("+a.translateX+
"px, "+(a.translateY+h)+"px, "+(a.translateZ+h)+"px)",delay:i,time:a.dur1,ease:a.ease1,origin:"center center",add:"left, top"},function(){d(this).css({left:a.width/a.vPieces*b,top:0}).csTransform({transform:"rotateX(-90deg) rotateY(0deg) rotateZ(0deg) scaleZ(1)  scaleY(1) scaleX(1) translate3d(0px,"+a.height/2+"px,"+a.height/2+"px)",time:a.dur3,delay:a.xFadeDelay,ease:a.ease2,origin:"center center",add:"left, top"},function(){b==(a.startFrom>g/2?0:a.vPieces-1)&&n()})})})});break;case "horizontal3D":k=
h.find(".dummy-first");r=h.find(".dummy-last");for(e=1;e<=a.hPieces;e++)k.append('<div><div class="cs-top-face"></div><div class="cs-bot-face"></div><div class="cs-left-face"></div><div class="cs-old-face"></div><div class="cs-new-face"></div></div>');h.css({"-webkit-perspective":"1200","-webkit-perspective-origin":"50% 50%",perspective:"1200","perspective-origin":"50% 50%"});a.animateContainer&&(h.css({"-webkit-perspective":"1200",perspective:"1200"}),v="rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleX(1) scaleY(1) scaleZ(1) translate3d(0px,0px,0px)",
k.csTransform({transform:v,delay:100,time:0,origin:"50% 50%"},function(){d(this).css({"-webkit-transform-style":"preserve-3d","transform-style":"preserve-3d"}).csTransform({transform:a.animateContainer,time:a.dur1,delay:0,origin:"50% 50%"},function(){d(this).csTransform({time:a.dur3,delay:a.containerDelay,transform:v,origin:"50% 50%"})})}));k.children("div").each(function(){var b=d(this).index();d(this).css({width:a.width,height:a.height/a.hPieces,position:"absolute",top:a.height/a.hPieces*b,left:0,
zIndex:b>=a.hPieces/2?-b:b,"transform-style":"preserve-3d","-webkit-transform-style":"preserve-3d","-webkit-perspective-origin":"50% 50%","perspective-origin":"50% 50%"}).children("div.cs-old-face").each(function(){d(this).css({width:a.width,height:a.height/a.hPieces,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",top:0,left:0,zIndex:9,"background-image":"url("+u.find("img").attr("src")+")",backgroundPosition:"left "+(-a.height/a.hPieces*b+"px")}).csTransform({transform:"rotateX(0deg)",
origin:"center bottom"})}).end().children("div.cs-new-face").each(function(){d(this).css({width:a.width,height:a.height/a.hPieces,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,"background-image":"url("+o.find("img").attr("src")+")",backgroundPosition:"left "+(-a.height/a.hPieces*b+"px")}).csTransform({transform:"rotateY(90deg) translateX("+a.width+"px)",origin:"right center"})});a.showFaces&&d(this).children("div.cs-top-face").each(function(){d(this).css({width:a.width,
position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,height:a.width,background:a.t3D.faces.top}).csTransform({transform:"rotateX(90deg) translateY(-"+a.width+"px)",origin:"center top"})}).end().children("div.cs-bot-face").each(function(){d(this).css({width:a.width,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",zIndex:10,top:0,left:0,height:a.width,background:a.t3D.faces.bottom}).csTransform({transform:"rotateX(-90deg) translateZ("+
a.height/a.hPieces+"px) translateY(0px)",origin:"center top"})}).end().children("div.cs-left-face").each(function(){d(this).css({width:a.width,height:a.height/a.hPieces,position:"absolute","-webkit-backface-visibility":"hidden","backface-visibility":"hidden",top:0,left:0,background:a.t3D.faces.left,zIndex:-5}).csTransform({transform:"rotateY(-90deg) translateX(-900px)",origin:"left center"})});d(this).csTransform({transform:"rotateX(0deg) rotateY(0deg) rotateZ(0deg) scaleY(1) scaleX(1) scaleZ(1) translate3d(0px,0px,0px)",
delay:0,time:100,ease:a.ease1,origin:"center center",add:"left, top"},function(){if(a.hPieces>1)var f=!a.rotateSymmetric?-a.rotate+a.rotate*2*b/(a.hPieces-1):a.rotate,e=-a.rotateZ+a.rotateZ*2*b/(a.hPieces-1);else f=a.rotate,e=a.rotateZ;var g=a.hPieces;if(a.startFrom>=g-1)a.startFrom=g-1;if(a.startFrom==0)a.startFrom=0;var i=Math.abs(a.pieceDelay*(a.startFrom-b)),h=-a.width/2,j;j=h=h*a.rotateMid/-90;a.rotateMid<0&&(j=-1*h);d(this).css({top:(a.height+a.yOffset*2)/a.hPieces*b-a.yOffset,left:a.xOffset-
a.xOffset*2/a.hPieces*b}).csTransform({transform:"rotateX("+f+"deg) rotateY("+a.rotateMid+"deg) rotateZ("+e+"deg)  scaleX("+a.scaleX+") scaleY("+a.scaleY+") scaleZ("+a.scaleZ+") translate3d("+(a.translateX+h)+"px, "+a.translateY+"px, "+(a.translateZ+j)+"px)",delay:i,time:a.dur1,ease:a.ease1,origin:"center center",add:"left, top"},function(){d(this).css({left:0,top:a.height/a.hPieces*b}).csTransform({transform:"rotateX(0deg) rotateY(-90deg) rotateZ(0deg) scaleZ(1)  scaleY(1) scaleX(1) translate3d("+
-a.width/2+"px, 0px,"+a.width/2+"px)",time:a.dur3,delay:a.xFadeDelay,ease:a.ease2,origin:"center center",add:"left, top"},function(){b==(a.startFrom>=g/2?0:a.hPieces-1)&&n()})})})});break;default:var k=h.find(".dummy-first"),r=h.find(".dummy-last"),g=!1;a.type=="vertical"&&(g=!0);if(g)for(e=1;e<=a.vPieces;e++)k.append("<div ></div>"),q||r.append("<div ></div>");else for(e=1;e<=a.hPieces;e++)k.append("<div ></div>"),q||r.append("<div ></div>");q&&o.css({display:"block"});k.children("div").each(function(){var b=
d(this).index();d(this).css({width:g?a.width/a.vPieces:a.width,display:"block",position:"absolute",top:g?0:a.height/a.hPieces*b,left:g?a.width/a.vPieces*b:0,height:g?a.height:a.height/a.hPieces,"background-image":"url("+u.find("img").attr("src")+")",backgroundPosition:g?-a.width/a.vPieces*b+"px top":"left "+-a.height/a.hPieces*b+"px",opacity:1,borderRadius:"0px 0px 0px 0px"});if(C())d(this).csTransform({transform:"rotate(0deg) scaleY(1) scaleX(1) translate(0px,0px)",delay:20,time:0,ease:a.ease1,origin:a.origin,
add:"left, top, border-radius, opacity"},function(){var f="rotate("+(g?!a.rotateSymmetric?-a.rotate+a.rotate*2*b/(a.vPieces-1):a.rotate:!a.rotateSymmetric?-a.rotate+a.rotate*2*b/(a.hPieces-1):a.rotate)+"deg) scaleY("+a.scaleY+") scaleX("+a.scaleX+") translate("+a.translateX+"px,"+a.translateY+"px)",e=g?a.vPieces:a.hPieces;if(a.startFrom>=e-1)a.startFrom=e-1;if(a.startFrom==0)a.startFrom=0;var i=Math.abs(a.pieceDelay*(a.startFrom-b));d(this).css({left:g?(a.width+a.xOffset*2)/a.vPieces*b-a.xOffset:
a.xOffset-a.xOffset*2/a.hPieces*b,top:g?a.yOffset:(a.height+a.yOffset*2)/a.hPieces*b-a.yOffset,opacity:q?a.halfTransitionOpacity:1,borderRadius:l!="-o-"?a.borderRadius:""}).csTransform({transform:f,delay:i,time:a.dur1,ease:a.ease1,origin:a.origin,add:"left, top, border-radius ,opacity"},function(){q?b==(a.startFrom>e/2?0:g?a.vPieces-1:a.hPieces-1)&&n():r.css({display:"block"}).find("div:eq("+b+")").css({width:g?a.width/a.vPieces:a.width,position:"absolute",top:g?a.yOffset:(a.height+a.yOffset*2)/a.hPieces*
b-a.yOffset,left:g?(a.width+a.xOffset*2)/a.vPieces*b-a.xOffset:a.xOffset-a.xOffset*2/a.hPieces*b,height:g?a.height:a.height/a.hPieces,display:"none","background-image":"url("+o.find("img").attr("src")+")",backgroundPosition:g?-a.width/a.vPieces*b+"px top":"left "+-a.height/a.hPieces*b+"px",borderRadius:l!="-o-"?a.borderRadius:""}).csTransform({transform:f,delay:0,time:0,ease:a.ease2,origin:a.origin,add:"left, top, border-radius"},function(){d(this).delay(a.xFadeDelay).fadeIn(a.dur2,function(){k.children("div:eq("+
b+")").hide();d(this).css({left:g?a.width/a.vPieces*b:0,top:g?0:a.height/a.hPieces*b,borderRadius:"0px 0px 0px 0px"}).csTransform({transform:"rotate(0deg) scaleY(1) scaleX(1) translate(0px,0px)",time:a.dur3,delay:0,ease:a.ease2,origin:a.origin,add:"left, top, border-radius"},function(){b===(a.startFrom>e/2?0:g?a.vPieces-1:a.hPieces-1)&&n()})})})});l=="-o-"&&q&&d(this).delay(i).animate({"border-radius":a.borderRadius},a.dur1)});else{var f={left:g?(a.width+a.xOffset*2)/a.vPieces*b-a.xOffset:a.xOffset-
a.xOffset*2/a.hPieces*b,top:g?a.yOffset:(a.height+a.yOffset*2)/a.hPieces*b-a.yOffset,width:g?a.scaleX*d(this).width():a.scaleX*a.width,height:g?a.scaleY*d(this).height():a.scaleY*a.height/a.hPieces,opacity:q?a.halfTransitionOpacity:1},e=g?a.vPieces:a.hPieces;if(a.startFrom>=e-1)a.startFrom=e-1;if(a.startFrom==0)a.startFrom=0;var i=Math.abs(a.pieceDelay*(a.startFrom-b));d(this).delay(i).animate(f,a.dur1,function(){if(q)b==(a.startFrom>e/2?0:g?a.vPieces-1:a.hPieces-1)&&n();else{var f={left:g?a.width/
a.vPieces*b:0,top:g?0:a.height/a.hPieces*b,width:g?a.width/a.vPieces:a.width,height:g?a.height:a.height/a.hPieces};r.css({display:"block"}).find("div:eq("+b+")").css({width:g?d(this).width():a.scaleX*a.width,height:g?d(this).height():a.scaleY*a.height/a.hPieces,position:"absolute",top:g?a.yOffset:(a.height+a.yOffset*2)/a.hPieces*b-a.yOffset,left:g?(a.width+a.xOffset*2)/a.vPieces*b-a.xOffset:a.xOffset-a.xOffset*2/a.hPieces*b,display:"none","background-image":"url("+o.find("img").attr("src")+")",backgroundPosition:g?
-a.width/a.vPieces*b+"px top":"left "+-a.height/a.hPieces*b+"px"}).delay(a.xFadeDelay).fadeIn(a.dur2,function(){k.children("div:eq("+b+")").hide()}).animate(f,a.dur3,function(){b==(a.startFrom>e/2?0:g?a.vPieces-1:a.hPieces-1)&&n()})}})}})}}}if(this.length!=0){d.chopSlider={};b||(b={});b.autoplay=b.autoplay||!1;b.autoplayDelay=b.autoplayDelay||1E4;b.useCaptions=b.useCaptions||!1;b.captionTransform=b.captionTransform||"";b.rotate=b.rotate||0;b.scaleY=b.scaleY||b.scaleY===0?b.scaleY:1;b.scaleX=b.scaleX||
b.scaleX===0?b.scaleX:1;b.borderRadius=b.borderRadius||"0px 0px 0px 0px";b.translateX=b.translateX||b.translateX===0?b.translateX:0;b.translateY=b.translateY||b.translateY===0?b.translateY:0;b.ease1=b.ease1||"ease";b.ease2=b.ease2||"ease";b.origin=b.origin||"50% 50%";b.xOffset=b.xOffset||0;b.yOffset=b.yOffset||0;b.startFrom=b.startFrom||0;b.hPieces=b.hPieces>0?b.hPieces:10;b.vPieces=b.vPieces>0?b.vPieces:10;b.dur1=b.dur1>=0?b.dur1:1E3;b.dur2=b.dur2>=0?b.dur2:600;b.dur3=b.dur3>=0?b.dur3:1E3;b.type=
b.type||"vertical";b.rotateSymmetric=b.rotateSymmetric===!0||b.rotateSymmetric===!1?b.rotateSymmetric:!0;b.disableCSS3=b.disableCSS3===!0||b.disableCSS3===!1?b.disableCSS3:!1;b.pieceDelay=b.pieceDelay>=0?b.pieceDelay:50;b.multiDelay=b.multiDelay||"progressive";b.xFadeDelay=b.xFadeDelay>=0?b.xFadeDelay:300;b.hideTriggers=b.hideTriggers===!0||b.hideTriggers===!1?b.hideTriggers:!0;b.hideCaptions=b.hideCaptions===!0||b.hideCaptions===!1?b.hideCaptions:!0;b.activeSlideClass=b.activeSlideClass||"cs-activeSlide";
b.activeQClass="."+b.activeSlideClass;b.activePaginationClass=b.activePaginationClass||"cs-active-pagination";b.activeQPaginationClass="."+b.activePaginationClass;b.mobileUAs=b.mobileUAs||"ndroid,iPhone,iPod,BlackBerry,Symbian,Mobile".split(",");b.defaultParameters&&d.extend(b,b.defaultParameters);if(b.mobile&&F()&&b.mobile.disableCSS3)b.disableCSS3=b.mobile.disableCSS3;for(var E in b)if(E=="random")b.random=!0;d.chopSlider.isMobile=function(){return F()};d.chopSlider.redefine=function(f){if(f)c=
{},d.extend(c,b,f),b=c,b.autoplay===!1?(clearTimeout(d.chopSlider.autoplay),b.autoplay=!1):G()};var l="";(function(){d("body").append('<div class="chopSlider-css3Test"></div>');var b=d(".chopSlider-css3Test")[0].style,a=b.transition!==void 0||b.WebkitTransition!==void 0||b.MozTransition!==void 0||b.MsTransition!==void 0||b.OTransition!==void 0;b.WebkitTransition!==void 0&&(l="-webkit-");b.MozTransition!==void 0&&(l="-moz-");b.MsTransition!==void 0&&(l="-ms-");b.OTransition!==void 0&&(l="-o-");d.chopSlider.hasCSS3=
function(){return a};if(a){var i=!1;"webkitPerspective"in b&&(i=!0);"MozPerspective"in b&&(i=!0);"OPerspective"in b&&(i=!0);"MsPerspective"in b&&(i=!0);"perspective"in b&&(i=!0);if(i){b=d('<style media="(transform-3d), (-moz-transform-3d), (-webkit-transform-3d), (-o-transform-3d), (-ms-transform-3d)">div.chopSlider-css3Test { overflow: hidden }</style>');d("head").append(b);var h=!1;d(".chopSlider-css3Test").css("overflow")=="hidden"&&(h=!0);b.remove()}d.chopSlider.has3D=function(){return h}}else d.chopSlider.has3D=
function(){return!1};d(".chopSlider-css3Test").remove()})();d.fn.csTransform=function(b,a){var i,h;if(!C())return this;if(arguments.length==0)return this;if(arguments.length==3)i=void 0,h=void 0,i=arguments[0],h=arguments[1],a=arguments[2],b={},b.transform=i,b.time=h;if(arguments.length<=2)typeof b=="string"?(i=void 0,h=void 0,i=arguments[0],arguments.length==2?typeof arguments[1]=="number"||typeof arguments[1]=="string"?(h=arguments[1],a=""):(h=0,a=arguments[1]):h=0,b={},b.transform=i,b.time=h):
(b.time=b.time||0,b.transform=b.transform||"");b.delay=b.delay||0;b.ease=b.ease||"ease";b.origin=b.origin||"50% 50%";a&&(new H(this,a,b)).runCallback();if(b.add){b.add.replace("{bp}",l);var m=", "+b.add}else m="";return this.each(function(){d(this).css(l+"transform",b.transform).css(l+"transition-property",l+"transform"+(b.animateOrigin?" ,"+l+"transform-origin":"")+m).css(l+"transition-duration",b.time/1E3+"s").css(l+"transition-delay",""+b.delay/1E3+"s").css(l+"transition-timing-function",""+b.ease).css(l+
"transform-origin",""+b.origin)})};var D=0;d.chopSlider.isAnimating=function(){return D};y=void 0;z=void 0;h=void 0;var s=this;b.container=d(s);b.width=s.width();b.height=s.height();d("body").append('<div class="cs-slider-loader" style="display:none"></div>');h=d(".cs-slider-loader:last");h.html('<div class="dummy-blocks" style="position:relative"><div class="dummy-first" style="width:'+b.width+"px;height:"+b.height+'px"></div><div class="dummy-last" style="display:none;position:absolute;left:0px;top:0px;"></div></div>');
b.sliderLoader=h;var m=b.slide||".slide";d.chopSlider.slide=function(f){var a={};f?d.extend(a,b,f):a=f=b;if(!f.direction)f.direction="next";clearTimeout(d.chopSlider.autoplay);a.autoplay=!1;B(f.direction,a,f.slideTo)};b.autoplay&&G();b.useCaptions&&(E=d(b.everyCaptionIn).eq(d(b.slide+b.activeQClass).index()).html(),d.trim(E)!=""&&d(b.showCaptionIn).show().html(E));h.css({left:s.offset().left,top:s.offset().top,position:"absolute","z-index":b.loaderIndex>=0?b.loaderIndex:2E4,width:b.width,height:b.height,
display:"none"});d(window).resize(function(){h.css({left:s.offset().left,top:s.offset().top})});y=d(b.nextTrigger);z=d(b.prevTrigger);y.click(function(f){clearTimeout(d.chopSlider.autoplay);b.autoplay=!1;f.preventDefault();B("next",b)});z.click(function(f){clearTimeout(d.chopSlider.autoplay);b.autoplay=!1;f.preventDefault();B("prev",b)});b.sliderPagination&&(d(b.sliderPagination).eq(d(b.activeQClass).index()).addClass(b.activePaginationClass),d(b.sliderPagination).click(function(f){f.preventDefault();
var f=d(this),a=d(b.activeQPaginationClass).index();if(!f.hasClass(b.activePaginationClass))clearTimeout(d.chopSlider.autoplay),b.autoplay=!1,a=f.index()>a?"next":"prev",B(a,b,f.index())}))}}})(jQuery);